dist: xenial
language: python
cache: false

env:
  global:
    # pytest: uses --color=yes to force colors on Travis/Windows (requires
    # colorama also (uninstalled with nocolorama tox env)).
    - PYTEST_ADDOPTS="-vv --color=yes"
    - PIP_DISABLE_PIP_VERSION_CHECK=true

stages:
  - name: test
    if: tag IS NOT present
  - name: release
    if: tag IS present

jobs:
  include:
    - name: Windows
      os: windows
      language: shell
      before_install:
        - choco install --no-progress python
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - TOXENV=uses_custom_script
        - PYTEST_ADDOPTS="$PYTEST_ADDOPTS --cov-append"
      script:
        - cmd.exe /C 'python.exe -m tox -e py37-coverage'
        - cmd.exe /C 'python.exe -m tox -e py37-nocolorama-coverage'
        - tox -e py37-coverage
        - tox -e py37-nocolorama-coverage
        - tox -e py37-coverage -- -s
        - tox -e py37-nocolorama-coverage -- -s

    - os: osx
      osx_image: xcode10.2
      language: generic
      env: TOXENV=py37-coverage
      before_install:
        - ln -sfn "$(which python3)" /usr/local/bin/python
        - python -V
        - test $(python -c 'import sys; print("%d%d" % sys.version_info[0:2])') = 37

    - python: 'pypy'
      env: TOXENV=pypy-coverage
    - python: 'pypy3'
      env: TOXENV=pypy3-coverage
    - python: '3.7'
      env: TOXENV=py37-coverage
    - python: '3.6'
      env: TOXENV=py36-coverage
    - python: '3.5'
      env: TOXENV=py35-coverage
    - python: '3.4'
      env: TOXENV=py34-coverage
    - python: '2.7'
      env: TOXENV=py27-coverage
    - python: '3.8-dev'
      env: TOXENV=py38-coverage

    - python: '3.7'
      env: TOXENV=checkqa

    - stage: release
      python: '3.7'
      script: skip
      install: skip
      deploy:
        provider: pypi
        user: antocuni
        password:
          secure: EE0ETWh9RqPr8yF0GeoXYg8zTVaZj23zpIFyHaWshMnnqg6s42QARB4CGrBiXwqjqwL262JV+PruSynOkIpsi8p9r4lju51EwjHWOEmD5qd+2SzAD+XinQD074lA08nayKohk3qVS/ebWKPrVH0lJT7bIZvyN8W6UDhkw6/3P91ixxn7tPgDX0FJpRQpbyc8TXP25GXYMpOyANIV/qtRXHylGtS7aeAJMcVD5HlE+EEXxMQhF5MK+mvmTXuC+WGAtM36Vm48kyLVfalvQEGWY/v1UDq7dKua/EZleoLxSIJ4c6XKnx6zIoYNyKJeJiaYuutb6TYTYKQ18ZVU6jaAKE5wu/9szMIw+XMtud1J9W7Co/UgILR6AZKq/OKd7Kl1eQlF/OU1lXnU5q9wseunxkjVaA/W0tnmzHi95KKV0FebXBYPqA/ybk69tc9nsIBwxH4sNrUv5DtA7WX43WhGxN91nNhfbW3CsTklwbqrrHRkbCB2vCP+JVkQ1ctOwX7XPv+ghLqhetFsvNGNEEk/h9Vo3hiR0iq1g7MMXgqASZ/QSrSvxVbBSdB+hLt5QaS4FIRuHDaMNCD8bH3VumneLgsdaKlg0iELUvC7JyqcdRYQowZbOSlNKwSH6ys3TGyQ5DWnrGWp3Hb1YfU27cweuApZZsg1O3xEC5AMTP1FJbY=
        on:
          tags: true
          distributions: 'sdist bdist_wheel'
          repo: antocuni/pdb

install:
  - pip install tox==3.12.1
  # NOTE: need to upgrade virtualenv to allow "Direct url requirement" with
  # installation in tox.
  - pip install virtualenv==16.6.0

before_script:
  - pip --version
  - pip freeze

script:
  - tox

after_script:
  - |
    if [[ "$TOXENV" != checkqa ]]; then
      # Unset TRAVIS_CMD to work around https://github.com/codecov/codecov-bash/issues/174.
      env -u TRAVIS_CMD bash <(curl -s https://codecov.io/bash) -Z -X gcov -X coveragepy -X search -X xcode -X gcovout -X fix -f coverage.xml -n "${TRAVIS_PYTHON_VERSION}" -F "${TRAVIS_OS_NAME}"
    fi

branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
