dist: xenial
language: python
cache: false

env:
  global:
    - PYTEST_ADDOPTS=-vv
    - PIP_DISABLE_PIP_VERSION_CHECK=true

stages:
  - name: test
    if: tag IS NOT present
  - name: release
    if: tag IS present

jobs:
  include:
    - name: Windows (colorama)
      os: windows
      language: shell
      before_install:
        - choco install python
        # - python -m pip install --upgrade pip
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - TOXENV=py37-coverage,py37-colorama-coverage

install:
  - pip install tox==3.12.1
  # NOTE: need to upgrade virtualenv to allow "Direct url requirement" with
  # installation in tox.
  - pip install virtualenv==16.6.0

before_script:
  - pip --version
  - pip freeze

script:
  - tox

after_script:
  - |
    if [[ "$TOXENV" != checkqa ]]; then
      # Unset TRAVIS_CMD to work around https://github.com/codecov/codecov-bash/issues/174.
      env -u TRAVIS_CMD bash <(curl -s https://codecov.io/bash) -Z -X gcov -X coveragepy -X search -X xcode -X gcovout -X fix -f coverage.xml -n "${TRAVIS_PYTHON_VERSION}" -F "${TRAVIS_OS_NAME}"
    fi

branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
